[package]
name = "kenn-config"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
directories = "6"
globset.workspace = true
tracing.workspace = true
xxhash-rust.workspace = true

[dev-dependencies]
tempfile.workspace = true
